baseURL = 'https://norbmor.netlify.app/'
languageCode = 'en-us'
title = 'Norberto Moreno-Quib√©n - My academic site'
theme = 'PaperMod' # Or whatever theme name you downloaded

[[menu.main]]
  name = 'Curriculum Vitae'
  url = '/cv/'
  weight = 10

[[menu.main]]
  name = 'Research'
  url = '/research/'
  weight = 20

[[menu.main]]
  name = 'Teaching'
  url = '/teaching/'
  weight = 30
